### PR TITLE
feature(Testing) [NB] Add Rspec test suite, include coverage of Spect…

### PR DESCRIPTION
**Pull request by NB28VT**
…ator

Still haven't quite found a way to get the file testing working. Will likely involve the file_fixture helpers in ActionDispatch somehow.

### CODE REVIEW

**Review by ozydingo — COMMENTED** [review]
I have definitely had it in my head to be able to have the non-Rails parts of this gem live separately -- adding any Rails / ActionPack dependenceies is huge for how small this gem is! For the current purpose -- if we don't test full controller actions and we don't test the file upload, can we get away with not adding any of these dependencies? If so we can definitely get that in as a first PR that can get merged asap, then we can talk about adding the Rails-dependent test coverage.

**Comment by ozydingo** [comment]
Also please note: required for one of our 3play apiv3 things, I added an `array` keyword -- similar to `arrayable`, but will *always* arrayify, whereas `arrayable` will only arrayify if there is a comma. Quick think to add to the list of tests.

**Comment by NB28VT** [comment]
"adding any Rails / ActionPack dependenceies is huge for how small this gem is! "

Totally agree!

"if we don't test full controller actions and we don't test the file upload, can we get away with not adding any of these dependencies?"

Not quite, not if you want to use `deep_dup` and `append` in the gem and write a test suite for it independently. They rely on that `active_support/core_ext/object/deep_dup` and ActiveRecord itself, respectively. I could investigate requiring less of ActiveRecord, but `append` (from 'CollectionProxy `) seemed to interact with so much of ActiveRecord, I thought that would turn into a bit of a rabbit hole.

ActionPack is part of the approach I'm trying for the file object (so we can get an `UploadedFile` object).
Here's one resource I found for that approach:
https://collectiveidea.com/blog/archives/2017/01/16/testing-an-uploaded-file-in-rspec

So ActionPack can go but the other two need to get loaded. Unless we stub the deep dup and append. Not impossible, but how far do you want to get from what's actually happening when this is loaded into a Rails app?

Plugins are a neat possibility, but that would be a heavyweight gem with a dummy Rails app in it. 
http://guides.rubyonrails.org/plugins.html

However, if you're looking to extend ActionController anyway, doesn't that seem like an attractive option? It would certainly be easier to test.

**Comment by NB28VT** [comment]
@ozydingo summary of latest changes/cleanup:
* Mark `Me` tests as pending so you can run the whole test suite without any failures.
* Ditch append in favor of unshift
* Remove dependencies on Rails libraries
* I wrote two tests for `any` in `Spectator`

**Comment by ozydingo** [comment]
Please reopen as a PR onto `development`

**Pull request closed without merging**
